name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: nix flake check
        run: nix flake check
